### ISSUE TITLE
issue with pip install: deepargs predict bug

### ISSUE THREAD

**Issue by ewissel** [gaarangoa/deeparg2.0#5]
I built a conda env with the following commands: 
```
conda create -n deeparg_env python=2.7.18 
conda activate deeparg_env 
conda install -c bioconda diamond==0.9.24 
pip install deeparg==1.0.2 
deeparg download_data -o /path/to/local/directory/ 
```

I try to run `deeparg predict -i sim_dat/fasta/contigs.fasta -o deeparg_out_combo_fasta --model SS` and get the following error:

```
/home/ewissel/miniconda3/envs/deeparg_env/lib/python2.7/site-packages/theano/tensor/signal/downsample.py:6: UserWarning: downsample module has been moved to the theano.tensor.signal.pool module.
  "downsample module has been moved to the theano.tensor.signal.pool module.")
/home/ewissel/miniconda3/envs/deeparg_env/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
INFO:root:DIAMOND blastx alignment
Traceback (most recent call last):
  File "/home/ewissel/miniconda3/envs/deeparg_env/bin/deeparg", line 8, in <module>
    sys.exit(main())
  File "/home/ewissel/miniconda3/envs/deeparg_env/lib/python2.7/site-packages/deeparg/entry.py", line 184, in main
    args.func(args)
  File "/home/ewissel/miniconda3/envs/deeparg_env/lib/python2.7/site-packages/deeparg/entry.py", line 36, in predict
    '-d', args.data_path+"/database/"+args.model_version+"/features",
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

This seems to be a bug with the pip install of deepargs. Let me know if this package is actively maintained and if you plan to fix this soon!

**Comment by hugomiguell** [comment]
Hi ewissel, you need to add the option -d /path/to/local/directory/ to deeparg know the location of the databases downloaded in the previous step.

**Comment by ewissel** [comment]
That fixed it, thanks!!
